[Reservoir Selection]
RESERVOIR_GRAND_ID = 1195

[Data Sources]
REFERENCE_CURVES = input/reference_curves/grdl
;EE_PROJECT = ee-hishameldardiry
EE_PROJECT = cosmic-descent-489809-a1


[Simulation Period]
START_YEAR = 2021
END_YEAR = 2022

[Simulation Settings]
PIXEL_AREA_KM2 =  0.0009